xxl:
  job:
    admin:
      addresses: http://192.168.4.164:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
    accessToken: